Feature/issue 3 thinh
saigon-tech/laravel-exercise pull request #15
Opened 2021-09-01 04:01 UTC by tcthinhsqt

2021-09-01 06:50 UTC, tantai0809 requested changes
@tcthinhsqt 
I have some comments, please check !!!

2021-09-01 06:50 UTC, tantai0809 commented on backend/app/Models/Student.php
> +//    }
@tcthinhsqt 
please remove if unuse

2021-09-06 03:32 UTC, tantai0809 requested changes
I have comment, but please fix it in next issue

2021-09-06 03:32 UTC, tantai0809 commented on backend/app/Http/Requests/SearchStudentRequest.php
> +}
@tcthinhsqt 
please remove if don't use

2021-09-06 03:39 UTC, tcthinhsqt commented on backend/app/Http/Requests/SearchStudentRequest.php
> +}
ok i got it

2021-09-06 06:20 UTC, closed without merging