Feature/issue 4 thinh
saigon-tech/laravel-exercise pull request #16
Opened 2021-09-06 04:39 UTC by tcthinhsqt

2021-09-06 07:46 UTC, hdkhoasgt requested changes
@tcthinhsqt 
Please confirm 🙇

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Http/Controllers/AdminController.php
> +    public function index(Request  $request) {
@tcthinhsqt 
Please add PHP-doc for all functions

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Http/Controllers/AdminController.php
> +        if (Auth::attempt($validated)) {
@tcthinhsqt 
You can use `$request->validated()`

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Http/Controllers/AdminController.php
> +            return redirect()->back()->withErrors('Sai tên tài khoản hoặc mật khẩu!')->withInput();
@tcthinhsqt 
Please use the lang values. 
Do not use const value in the source code. Add to lang or config.

File: backend/resources/lang/en/auth.php

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/routes/web.php
> +
@tcthinhsqt 
Please change to below.
```
Route::resource('/admin/students', 'StudentController')->middleware('auth');
``` 
https://laravel.com/docs/7.x/controllers#resource-controllers

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Http/Middleware/RedirectIfAuthenticated.php
> +            return redirect()->route('student.index');
@tcthinhsqt 
Please revert this change. Change the value of `RouteServiceProvider::HOME `

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Models/Grade.php
> +    public function Student() {
@tcthinhsqt 
Please follow naming conventions
https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Models/Grade.php
> +        return $this->belongsTo('App\Models\Student', 'student_id', 'id');
@tcthinhsqt 
```suggestion
        return $this->belongsTo(Student::class, 'student_id', 'id');
```

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Models/Student.php
> +    public function Grade() {
@tcthinhsqt
Please follow naming conventions
https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Models/Student.php
> +        return $this->hasMany('App\Models\Grade', 'student_id', 'id');
@tcthinhsqt 
```suggestion
        return $this->hasMany(Grade::class, 'student_id', 'id');
```

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/config/auth.php
>              'model' => App\User::class,
@tcthinhsqt 
Just change this class to `App\Models\Admin::class`

Revert this file

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/database/seeds/AdminsSeeder.php
> +            'email' =>  'taikhoan@gmail.com'
@tcthinhsqt 
Requirement is admin/admin/admin@gmail.com

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/database/seeds/DatabaseSeeder.php
> +        $this->call(AdminsSeeder::class);
@tcthinhsqt 
Please add factory for Student table. Create 500 students.

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/app/Http/Requests/AdminRequest.php
> +            'username' => 'bail|required|min:6',
@tcthinhsqt 
Do not check min length here. It's for creating and updating.

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/resources/views/Layout/layout.blade.php
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
@tcthinhsqt 
Move the js files to bottom of file

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/resources/views/Layout/layout.blade.php
> +@stack('js')
@tcthinhsqt 
Move this stack to after all js imports

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/resources/views/Student/adminlogin.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
@tcthinhsqt
Please follow naming conventions
https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions
https://laravel.com/docs/7.x/controllers#resource-controllers

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/resources/views/welcome.blade.php
> -
@tcthinhsqt 
Please revert this file. Do not exist in requirement

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/routes/web.php
> +//Route::resource('/admin/student', 'StudentController')->middleware('auth');
@tcthinhsqt 
Please remove prefix admin.

2021-09-06 07:46 UTC, hdkhoasgt commented on backend/routes/web.php
> +//Route::resource('/admin/student', 'StudentController')->middleware('auth');
@tcthinhsqt 
Please follow https://laravel.com/docs/7.x/controllers#resource-controllers

2021-09-07 11:55 UTC, hdkhoasgt requested changes

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/welcome.blade.php
> -
@tcthinhsqt 
Just revert. Not remove it. Please

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/routes/web.php
>  });
@tcthinhsqt 
Please add WelcomeController for this route

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/routes/web.php
> +    ->middleware('auth');
@tcthinhsqt 
Please remove this route. Search by `student.index` route

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/routes/web.php
> +Route::get('logout', ['as' => 'logout', 'uses' =>'AdminController@logout']);
@tcthinhsqt 
Use POST for this route

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/test-login.blade.php
> +<p>Đăng nhập thành công</p>
@tcthinhsqt 
Please remove this file

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/package-lock.json
> -{
@tcthinhsqt 
Please revert this file

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/public/css/adminlogin.css
> +form {
@tcthinhsqt 
Please rename to ` backend/public/css/admin/login.css`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/public/css/createform.css
> +form {
@tcthinhsqt 
Please rename to `backend/public/css/student/create.css`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/public/css/studentmanager.css
> +#searchdiv {
@tcthinhsqt
Please rename to backend/public/css/student/index.css

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/layout/layout.blade.php
> +            /*align-items: center !important;*/
@tcthinhsqt 
Please remove this comment

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/admin-login.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
@tcthinhsqt 
Please rename to `backend/resources/views/admin/login.blade.php`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/admin-login.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
@tcthinhsqt 
Fix the comment

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/layout/layout.blade.php
> +    This is the master sidebar.
@tcthinhsqt 
Please add to lang file

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/admin-login.blade.php
> +@section('title', 'Admin login')
@tcthinhsqt 
Please add to lang file `'Admin login'`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/admin-login.blade.php
> +        <button name="submit" type="submit">LOGIN</button>
@tcthinhsqt 
Please add to lang file `LOGIN`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/create-form.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
@tcthinhsqt 
Rename to `backend/resources/views/student/create.blade.php`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/admin-login.blade.php
> +        <button name="submit" type="submit">LOGIN</button>
@tcthinhsqt 
Please add all text to lang file

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/edit-form.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
@tcthinhsqt 
Rename to `backend/resources/views/student/edit.blade.php`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/resources/views/student/student.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
@tcthinhsqt 
Rename to `backend/resources/views/student/index.blade.php`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/app/Http/Requests/StoreStudentRequest.php
> +<?php
@tcthinhsqt 
Rename to `backend/app/Http/Requests/Student/StoreRequest.php`

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/config/auth.php
> +            'model' => App\Models\Admin::class,
@tcthinhsqt 
Keep only this change. revert others in this file

2021-09-07 11:55 UTC, hdkhoasgt commented on backend/database/seeds/GradesSeeder.php
> +<?php
@tcthinhsqt 
Please remove this file

2021-09-09 11:22 UTC, hdkhoasgt commented on backend/app/Http/Controllers/WelcomeController.php
> +        return redirect()->route('student.index');
@tcthinhsqt 
Please render view welcome.blade.php

2021-09-09 11:22 UTC, hdkhoasgt commented on backend/resources/lang/en/student-form.php
> +<?php
@tcthinhsqt 
Rename to `backend/resources/lang/en/student.php `

2021-09-09 11:22 UTC, hdkhoasgt commented on backend/resources/lang/en/slide-bar.php
> +    // resources/lang/en/slide-bar.php
@tcthinhsqt
Rename to `backend/resources/lang/en/sidebar.php`

2021-09-09 11:22 UTC, hdkhoasgt commented on backend/resources/views/student/student.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
@tcthinhsqt 
Please fix this

2021-09-09 12:17 UTC, hdkhoasgt requested changes
@tcthinhsqt 
Please confirm 
Read spec carefully https://docs.google.com/spreadsheets/d/12Z4jH4arqmLzo232QT618ao0Gc-n-aSPwBXnwTMW46o/edit#gid=2035710556&range=K3

 - [x] Per page 10
 - [ ] Birthday (Y/m/d)
 - [ ] Button first and last at pagination
 - [x] GPA format (##.#)
 - [x] Column search - show desc or asc

<img width="1362" alt="Screen Shot 2021-09-09 at 19 09 30" src="https://user-images.githubusercontent.com/40014186/132683365-90c34888-156b-4994-947b-b3e245cc5dc9.png">


Column sort example
<img width="841" alt="Screen Shot 2021-09-09 at 19 16 47" src="https://user-images.githubusercontent.com/40014186/132684124-748ced5f-1015-44f3-9d50-7c1a86c88677.png">

2021-09-09 12:17 UTC, hdkhoasgt commented on backend/app/Http/Controllers/StudentController.php
> +use Facade\Ignition\Support\Packagist\Package;
@tcthinhsqt 
Please remove unsed lib

2021-09-09 15:23 UTC, tcthinhsqt commented on backend/database/seeds/GradesSeeder.php
> +<?php
I have already removed this file before

2021-09-09 15:23 UTC, tcthinhsqt commented on backend/resources/views/student/student.blade.php
> +<!-- Stored in resources/views/child.blade.php -->
Done

2021-09-09 15:57 UTC, tcthinhsqt commented on backend/app/Http/Requests/Student/StoreRequest.php
> +        $after_date = '1990-01-01';
please grant me the permission of this document to access
https://docs.google.com/spreadsheets/d/12Z4jH4arqmLzo232QT618ao0Gc-n-aSPwBXnwTMW46o/edit#gid=2035710556&range=K3

2021-09-10 12:09 UTC, hdkhoasgt requested changes
@tcthinhsqt 
Please fix 
 - Birthday (Y/m/d)
 - Button first and last at pagination
 - GPA format (##.#) (04.0 -> 4.0) -> do not add leading zero
 - Column search - show desc or asc (Does not keep order when click search or refresh)
<img width="344" alt="Screen Shot 2021-09-10 at 19 07 37" src="https://user-images.githubusercontent.com/40014186/132851102-fefdd994-948f-4bfb-beee-9af20a28c861.png">

2021-09-13 07:12 UTC, hdkhoasgt commented on backend/app/Http/Requests/Student/StoreRequest.php
> +    }
@tcthinhsqt 
```
        return [
            'name'     => 'bail|required',
            'birthday' => 'bail|required|date|before:'.$maxBirthday.'|after:'.$minBirthday,
            'math'     => 'bail|required|integer|between:0,10',
            'music'    => 'bail|required|integer|between:0,10',
            'english'  => 'bail|required|integer|between:0,10',
        ];
```

2021-09-13 07:16 UTC, hdkhoasgt commented on backend/database/factories/StudentFactory.php
> +        'name' => substr($faker->firstName . ' ' . $faker->lastName,0, 20),
@tcthinhsqt 
Please format

2021-09-13 08:04 UTC, hdkhoasgt requested changes

2023-07-18 02:10 UTC, closed without merging