#1 Migration & Seeder DB
saigon-tech/laravel-exercise pull request #18
Opened 2023-07-19 03:51 UTC by vinhhc97

2023-08-03 07:49 UTC, ckthanh-sgt requested changes
@vinhhc97 
I've commented, please confirm

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/migrations/2023_07_19_081549_create_admins_table.php
> +        Schema::create('admins', function (Blueprint $table) {
@vinhhc97 
Please create model for `Admin`, `Grade`, `Student` in the following path `app/Http/Models/...php`
<img width="311" alt="image" src="https://github.com/saigon-tech/laravel-exercise/assets/67252507/d2ea2e70-8c5e-4787-a47b-7981dd7928db">

Docs:
https://laravel.com/docs/7.x/eloquent#defining-models

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/migrations/2023_07_19_081549_create_admins_table.php
> +            $table->string('email',20)->unique();
@vinhhc97 
Refactor code

- How to do:
Press combination of `command` + `option` + `L` at the same time

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/migrations/2023_07_19_082545_create_students_table.php
> +        });
@vinhhc97 
Refactor code for these lines

```
$table->id();
$table->string('name',20);
$table->date('birthday');
```

- How to do:
Press combination of `command` + `option` + `L` at the same time

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/migrations/2023_07_19_082723_create_grades_table.php
> +            $table->integer('grades');
@vinhhc97 
Refactor code for these lines:

```
$table->foreignid('student_id')->constrained('student.id');
$table->enum('subject', ['Math', 'Music', 'English']);
$table->integer('grades');
```

- How to do:
Press combination of `command` + `option` + `L` at the same time

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/migrations/2023_07_19_082723_create_grades_table.php
> +            $table->foreignid('student_id')->constrained('student.id');
@vinhhc97 
Wrong method for `$table->foreignid`

- Doc:
https://laravel.com/docs/7.x/migrations#creating-columns

<img width="777" alt="image" src="https://github.com/saigon-tech/laravel-exercise/assets/67252507/3717ad73-ae8b-43af-bb2b-8d9fbd1f5abe">

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/seeds/AdminSeeder.php
> +            'email'=>'vinh.hc@gmail.com'
@vinhhc97 
Refactor code for these lines

```
'username'=>'vinh',
'password'=>'123bonnamsau@@',
'email'=>'vinh.hc@gmail.com'
```

- How to do:
Press combination of `command` + `option` + `L` at the same time

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/seeds/DatabaseSeeder.php
>          // $this->call(UserSeeder::class);
@vinhhc97 
Remove unused line

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/seeds/GradeSeeder.php
> +        ]);
@vinhhc97 
Refactor code for these lines

- How to do:
Press combination of `command` + `option` + `L` at the same time

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/seeds/StudentSeeder.php
> +       ]);
@vinhhc97 
Refactor code for these lines

- How to do:
Press combination of `command` + `option` + `L` at the same time

2023-08-03 07:49 UTC, ckthanh-sgt commented on backend/database/seeds/StudentSeeder.php
> +       ]);
@vinhhc97 
Please create `Factory` for `Student`, `Admin`, `Grades` to create more data

- Docs:
https://laravel.com/docs/7.x/database-testing#generating-factories

2023-08-03 11:02 UTC, hdquangsgt reviewed
@vinhhc97 
Please check my comments

2023-08-03 11:02 UTC, hdquangsgt commented on backend/database/seeds/GradeSeeder.php
> +    }
@vinhhc97 
Please add record for GradeSeeder

2023-08-03 11:02 UTC, hdquangsgt commented on backend/database/seeds/DatabaseSeeder.php
> +        $this->call(StudentSeeder::class);
@vinhhc97 
GradeSeeder???

2023-08-04 06:32 UTC, hdquangsgt reviewed
@vinhhc97 
Please confirm

2023-08-04 06:32 UTC, hdquangsgt commented on backend/app/Grade.php
> +        ['student_id', 'subject', 'grade'];
@vinhhc97 
Please format code

2023-08-04 06:32 UTC, hdquangsgt commented on backend/app/Admin.php
> +        ['username', 'password', 'email',];
@vinhhc97 
Please format code

2023-08-04 06:32 UTC, hdquangsgt commented on backend/database/seeds/DatabaseSeeder.php
> +        $this->call(StudentSeeder::class);
@vinhhc97 
```suggestion
        $this->call([
            AdminSeeder::class, 
            StudentSeeder::class,
        ]);
```

2023-08-04 07:18 UTC, hdquangsgt approved these changes
@vinhhc97 
LGTM!

2023-08-04 07:18 UTC, merged